### ISSUE TITLE
Improve language of the abstract

### ISSUE THREAD

**Issue by csmarc** [openssi/peer-did-method-spec#10]
[[from RWOT8-Barcelona Peer DID Method Specification Report](https://github.com/WebOfTrustInfo/rwot8-barcelona/blob/master/draft-documents/peer-DID-method-spec-report.md)]
The language of the abstract is "marketing speak". We would suggest changing it to state just the intent.
"The method is cheap, fast, scalable, and secure" -> "The method is intended to be cheap, fast, scalable, and secure".

**Comment by dhh1128** [comment]
Will update.

**Comment by dhh1128** [comment]
This is fixed in PR #31 . See https://github.com/openssi/peer-did-method-spec/pull/31/commits/51b1ecff11407afe8ca3dbe7762e1770f5e071bd.
