### ISSUE TITLE
find a more permanent home for the spec?

### ISSUE THREAD

**Issue by dhh1128** [openssi/peer-did-method-spec#104]
In #82 , @Oskar-van-Deventer raised the question of the spec's permanent home. I have not been focused on that question, and I still don't know if it's an urgent question. But I wanted to open a ticket where the merits of finding one or more larger sponsors of the spec, and a place where the spec's github repo calls home, can be explored.

Some possible answers to this question include:

* At an SDO like W3C, Oasis, etc
* At an implementation org like DIF or Hyperledger
* At a less neutral org like Sovrin Foundation
* At a maximally neutral DID-related org like SSIMeetup
* With a conference's internet footprint (IIW, RWOT)
* Leaving it where it is ("openssi" as an org is as neutral as I could get on github)

**Comment by Oskar-van-Deventer** [comment]
Hi Daniel,

I agree that the question is not urgent now, as there are no major implementations or business dependencies. But once those are there, it may be too late.

As far as I can judge, openssi is an initiative by a few good-natured individuals without much formal governance. That should be fine for now, but I am not sure whether the term "neutral" is applicable, especially once the business interests start growing.

Given the open-source nature of Hyperledger, as part of the Linux Foundation, its well-established governance, and the fact that Peer DID is getting discussed at Hyperledger Aries anyway, that body would be my preference on the shorter term.

On the longer term, I see the open-source implementations remain with Hyperledger, while the specification could be maintained by a more formal organisation with more strict governance. It would be good to at least brainstorm a bit what would be arguments to go W3C, Oasis or other.

Oskar

**Comment by dhh1128** [comment]
The spec has moved to DIF: https://github.com/decentralized-identity/peer-did-method-spec
