### ISSUE TITLE
Clarify explanation of how to create groups

### ISSUE THREAD

**Issue by csmarc** [openssi/peer-did-method-spec#11]
[[from RWOT8-Barcelona Peer DID Method Specification Report](https://github.com/WebOfTrustInfo/rwot8-barcelona/blob/master/draft-documents/peer-DID-method-spec-report.md)]

In 1.2 Groups section, it should be made clear that if Alice and Bob are already connected (through peer DIDs), but wish to add another party, they should first create new peer DIDs with one another then invite Carol to that group.

Removing participants from a Group is basically recreating the group without the person who is 'removed'.

**Comment by dhh1128** [comment]
Excellent point. I will revise.

**Comment by dhh1128** [comment]
I updated the spec to address this concern. See #31 . Do you feel that the issue can be closed?

**Comment by csmarc** [comment]
Yes, the explanation is much better now. Also, the additional explainers are really good materials. I assume that over the longer term these materials could somehow be "more officially" incorporated into the whole peer DID spec. I know it would be simply too long to copy them into the spec, but I feel they are also a very crucial asset in understanding the spec.
