### ISSUE TITLE
Fix W3C references

### ISSUE THREAD

**Issue by jandrieu** [openssi/peer-did-method-spec#116]
The current spec, unfortunately, states that it is a W3C Editor's Draft and links to a dead-end /TR/ URL for the current version.

This makes it look like the specification is standards-track at the W3C, which to my knowledge isn't correct.

We are referencing this work in the RWOT paper, A Rubric for Decentralization of DID Methods, which we will be presenting to the DID WG for consideration. It would be great if we could get the specification cleaned up before the January DID WG face-to-face.

**Comment by dhh1128** [comment]
This has been fixed. Sorry it took me so long to revise the ticket status, and thanks for raising it.
