### ISSUE TITLE
pushback on global uniqueness requirement

### ISSUE THREAD

**Issue by dhh1128** [openssi/peer-did-method-spec#12]
Oskar D created the following doc to describe a concern: https://docs.google.com/document/d/1nnzAvF0tJgHtDut8GqcC6Fb_hXibV9JVyQbQ7suul60/edit

**Comment by Oskar-van-Deventer** [comment]
Ah thanks for including this issue.

**Comment by dhh1128** [comment]
Oskar, given the update in #25 , do you feel that this issue can be closed?

**Comment by Oskar-van-Deventer** [comment]
Yes, please close. Thanks!
