### ISSUE TITLE
List of reference implementations

### ISSUE THREAD

**Issue by OR13** [openssi/peer-did-method-spec#122]
I would love to see a list of implementations, and a conformance test suite for did peer, along with test vectors.

I'm happy to help maintain one of the implementations assuming I can see at least 1 other one :)

**Comment by javisantos** [comment]
Working on JavaScript implementation during weekends (to learn/understand) i'll let you know when the "parts" are public

One of them: https://www.npmjs.com/package/append-only-object

**Comment by javisantos** [comment]
https://github.com/javisantos/append-only-object
https://github.com/javisantos/faythe
https://github.com/javisantos/microledger

I'm `palying` implementing with a combination of this libraries

WIP

**Comment by OR13** [comment]
awesome!

is SGL 100% a requirement for did:peer ?

**Comment by javisantos** [comment]
Is what i understood from the specs

**Comment by dhh1128** [comment]
Closing now that the ticket is in its new repo home (https://github.com/decentralized-identity/peer-did-method-spec/issues/9).
