### ISSUE TITLE
Recognizing peer dids

### ISSUE THREAD

**Issue by davebryson** [openssi/peer-did-method-spec#128]
Trivial issue, but the Regex to match peer DIDs mentioned [here](https://openssi.github.io/peer-did-method-spec/index.html#recognizing-and-handling-peer-dids). (Example 3).  Will fail for `Method 0` peers.  It doesn't account for the multicodec value for the given public key format.   To handle both, the regex:
 
`^did:peer:[01](z)([1-9a-km-zA-HJ-NP-Z]{46, 47})$` 
appears to work.

**Comment by dhh1128** [comment]
Thank you for this comment. The spec has recently moved to https://github.com/decentralized-identity/peer-did-method-spec; I'll copy this ticket there.

**Comment by dhh1128** [comment]
Closing now that the ticket has been moved to its new repo home.
