### ISSUE TITLE
Add keyfmtchar example in Namestring Generation

### ISSUE THREAD

**Issue by csmarc** [openssi/peer-did-method-spec#13]
[[from RWOT8-Barcelona Peer DID Method Specification Report](https://github.com/WebOfTrustInfo/rwot8-barcelona/blob/master/draft-documents/peer-DID-method-spec-report.md)]

In Sec. 2.3 Namespace Specific Identifier, we understand the need for keyfmtchar, but it needs a definition, and an example of when to use it (i.e., when to make a "2") would be helpful. 
This issue is related to #2.

**Comment by dhh1128** [comment]
I believe PR #40 covered this, so I am closing the issue. If I'm wrong, please re-open.
