### ISSUE TITLE
Fix link in Sec 2.1 to "cross-registration" section at the end

### ISSUE THREAD

**Issue by csmarc** [openssi/peer-did-method-spec#15]
[[from RWOT8-Barcelona Peer DID Method Specification Report](https://github.com/WebOfTrustInfo/rwot8-barcelona/blob/master/draft-documents/peer-DID-method-spec-report.md)]

Fix link in Sec 2.1 ("later") to Sec. 6. Grafting Peer DIDs Into Another DID Method Namespace.

**Comment by dhh1128** [comment]
Thanks for the bug report!

This is fixed in PR #30 .
