### ISSUE TITLE
Enhance structure of Sec. 2.3 Namespace Specific Identifier 

### ISSUE THREAD

**Issue by csmarc** [openssi/peer-did-method-spec#16]
[[from RWOT8-Barcelona Peer DID Method Specification Report](https://github.com/WebOfTrustInfo/rwot8-barcelona/blob/master/draft-documents/peer-DID-method-spec-report.md)]

Section 2.3 could be better structured with subsections (e.g. for keyfmtstring and idstring).

**Comment by dhh1128** [comment]
Could you suggest an improvement in a PR?

**Comment by dhh1128** [comment]
@csmarc I really appreciate your careful listing of issues. I have added you as an author of the DID method spec (see https://github.com/openssi/peer-did-method-spec/pull/32/commits/81aa521de2c1c6fdac266dd9c0530abe391c1cb3). Please let me know if you prefer not to be listed. Also, please raise a PR to put a full name in that section of the doc for yourself, or tell me what you'd like me to add.

**Comment by csmarc** [comment]
@dhh1128, I opened PR #40 with my suggestion.
Thanks, you can add me as Marton Csernai.

**Comment by dhh1128** [comment]
PR was merged. Thank you!
