### ISSUE TITLE
Refer  an Appendix for keyfmtchar definitions

### ISSUE THREAD

**Issue by mavarley** [openssi/peer-did-method-spec#2]
Section 2.3
_This is "1", denoting a format where idstring is the upper 16 bytes of an Ed25519 public key. This gives idstring a length of either 21 or 22 base58 characters. This spec may be updated to include other keyfmtchar variants for SecP256, Curve448, or similar. Such updates might change the length of idstring as well._

All good - I would put a placeholder reference to an 'Appendix' where other keyfmts will be defined (similar to what I've seen in JOSE specs). I believe that for now these definitions can live as an appendix to this document (and not its own broken out spec) , because there is only "1" :)

**Comment by dhh1128** [comment]
@mavarley Good idea. Would you like to submit a PR? It would be easy to do this myself, but I'd love to get other contributors...

**Comment by dhh1128** [comment]
@mavarley : If you will submit a PR, I'd like to add you as an author of the DID method spec (see https://github.com/openssi/peer-did-method-spec/pull/32/commits/81aa521de2c1c6fdac266dd9c0530abe391c1cb3). Please let me know if you prefer not to be listed.

**Comment by dhh1128** [comment]
@mavarley , I've now edited the spec to cover this suggestion. I've also listed you as a contributor, and I've done major updates all over the spec. I would love your feedback.
