### ISSUE TITLE
Adding informational warnings about pairwise-anywise

### ISSUE THREAD

**Issue by Oskar-van-Deventer** [openssi/peer-did-method-spec#20]
I believe that it should be made explicit that developers should not make assumptions from a DID resolving method about its use.
o	did:sov DIDs could be used both pairwise and anywise
o	did:peer DIDs could be used both pairwise and anywise
We could include a note that states that publicly-resolvable (like did:sov) DIDs would typically be anywise, and non-publicly-resolvable DIDs (like did:peer) would typically be pairwise
That note could include a warning that developers should not assume an anywise or pairwise nature of a DID for its method alone.

**Comment by dhh1128** [comment]
Can you please propose some verbiage about this in a PR?

**Comment by Oskar-van-Deventer** [comment]
Done, see PR #39

**Comment by dhh1128** [comment]
PR is merged. Thank you!
