### ISSUE TITLE
Confusion with term "Peer DID"

### ISSUE THREAD

**Issue by Oskar-van-Deventer** [openssi/peer-did-method-spec#21]
When reading the document, I got a bit confused about the term “peer DID”.
-Can we explicitly state somewhere that the term is synonymous with “DID of the did:peer type”?
-Can we add a note somewhere that the term should not be confused with "pairwise DID”? After all, did:peer is not necessarily pairwise, pairwise DID are not necessarily did:peer.
-Can we add a note somewhere that the term should not be confused with “not publicly resolvable DID”? After all, also other DID methods may not be publicly resolvable, and maybe somebody builds a system to publicly resolve did:peer to aid key rollovers.

**Comment by dhh1128** [comment]
Good point. I have updated the verbiage with a paragraph about terminology near the top of the doc. See #29 . Do you agree that we could close this issue now?

**Comment by Oskar-van-Deventer** [comment]
Yes, your changes resolve the ambiguity. Thanks! Please close the issue.
