### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by Oskar-van-Deventer** [openssi/peer-did-method-spec#22]
Here are some (possible) typos

There is 
"publicKey": "ddid:peer:qQk1twjzCmEMgLDRN ..."
I assume the double d in "ddid" is a type

There is a hash "#" in 
"publicKey": "ddid:peer:qQk1twjzCmEMgLDRNmo7oS#1"
is that hash a typo, or a feature of DDO?

Why is the DID
"id": "did:peer:qQk1twjzCmEMgLDRNmo7oS"
different from
"for": "did:peer:rjHiqAzCbsNYhMZDTUASHg"
What is the semantics of each DID? Or is this just a typo?

**Comment by Oskar-van-Deventer** [comment]
See #24 for the first typo.

**Comment by dhh1128** [comment]
The PR for the first typo is fixed.
The hash is intentional. It refers to a specific key in the DID doc.
I will check on the third question.

**Comment by dhh1128** [comment]
There was indeed a typo related to your third point. This is now fixed and merged (see PR #27 ). @Oskar-van-Deventer , do you agree that we can close the ticket?

**Comment by Oskar-van-Deventer** [comment]
Thank you! Yes, please close.
