### ISSUE TITLE
Signing a public invitation

### ISSUE THREAD

**Issue by Oskar-van-Deventer** [openssi/peer-did-method-spec#23]
"The invitation is NOT encrypted, and it does NOT require the recipient (the invitee) to have special software that understands this protocol."

If an anywise DID is used, then can the public invitation be signed with a signing key from  the DDO associated with that DID? And would  such be useful?

Oskar
TNO - Techruption

**Comment by dhh1128** [comment]
Yes, and yes. This (the value of signing something that's unencrypted and sent over an insecure channel) is more or less the same observation that Tobias Looker has made in his work on the ephemeral challenge protocol in Indy. See https://github.com/hyperledger/indy-hipe/blob/42716a9ae990e7c04524269869164e776d01d876/text/ephemeral-challenge-protocol/README.md

Please submit a PR with some updated wording that can improve this section with your suggestion.

**Comment by Oskar-van-Deventer** [comment]
PR #41 submitted

**Comment by dhh1128** [comment]
Merged. Closing ticket.
