### ISSUE TITLE
Do we need a section on 'anchoring'?

### ISSUE THREAD

**Issue by mavarley** [openssi/peer-did-method-spec#3]
Section 2.1
_Furthermore, any direct or indirect anchoring of a peer DID to a specific blockchain is driven by circumstance and changeable at any time._

Do we need to provide guidance on this? (I think so...) and do we need an extension to the core DID spec to allow for DID linking/anchoring? (I'm not familiar enough with that spec...) For example, did:peer:1:347h3fnun9f2uh... has an entry in the attached DID Doc 
`"did_links": [ "did:sov:..." ]` or the like?

Happy to discuss further as to why this would even be necessary.

**Comment by dhh1128** [comment]
Here is an example of why anchoring to a blockchain could be useful: https://github.com/hyperledger/indy-hipe/blob/5885fea0b068060df1f4532eb20296edebf7f1aa/text/dkms/dkms-v4.md#95-dead-drops

**Comment by dhh1128** [comment]
There is now a Grafting section that covers this topic lightly.
