### ISSUE TITLE
Tidy up "Messages are serialized and encrypted" section

### ISSUE THREAD

**Issue by mavarley** [openssi/peer-did-method-spec#4]
Section 3.2

I think we can safely remove the words around "_However, nothing about this format is dependent on Indy. In particular, there are two implementations ..._" and expand on _"The format is as close as we could get to JWE conformance, but includes some extensions to handle multiplexed encryption_"

The explanation around various implementations of the connection protocol is important (it originally concerned me, for example) but I think if the spec focuses on why this connection protocol is required for this DID method we are fine. 

For example, "The connection-protocol extends JWEs and reuses an established method for INDY agents  to establishing connections that are transmission agnostic - but the connection protocol is not INDY specific. It defines a message structure and sequence and error cases that aligns with the DID Peer requirements outlined below. Multiplexed encryption, for example, is a feature of the connection-protocol that is important for peer DID messaging for... (group support?.. dunno)."  

Something like that?

**Comment by dhh1128** [comment]
@mavarley Thanks for the suggestion. I added a diagram and tried to tidy it up in the spirit of your recommendation, in particular explaining how multiplexing works and how it requires an extension to JWEs. See https://github.com/openssi/peer-did-method-spec/pull/6. Do you feel like we can close the issue?

If not, perhaps you could submit a PR to improve it?

**Comment by mavarley** [comment]
@dhh1128 looks great, closing!
