### ISSUE TITLE
Resolving peer DIDs that get anchored to a ledger

### ISSUE THREAD

**Issue by kdenhartog** [openssi/peer-did-method-spec#43]
In the case that a peer DID and associated DID document get anchored to a ledger, how is a resolver supposed to know the method for resolving this DID? Typically the DID method is associated with a way to resolve a DID and I think if we anchor peer DIDs to multiple ledgers it could create a problem. 

Assuming this were to occur, would the associated state change (history of the changes in the DID Doc) also be posted to the ledger? 

If we consider this a valid use case (I think it's better to just create a new on ledger DID instead), what I would suggest is that we update the the identifier to be name spaced to the ledger and then peer. For example `did:peer:NSI` is transformed to `did:sov:peer:NSI`. This opens a can of worms though that we may not want to explore right now.

**Comment by dhh1128** [comment]
This suggestion is now described in https://openssi.github.io/peer-did-method-spec/#grafting. Please let me know if you think the discussion there is adequate, or should be improved.

**Comment by kdenhartog** [comment]
I find that your comments on grafting thoroughly address how to handle this.  I'm not remembering the can of worms that I commented about at the end though. So if I think of it I'll make a pull request to that section, or reopen this issue with questions.
