### ISSUE TITLE
Note that Anywise DIDs are usually anchored on public ledger in the beginning of the Introduction

### ISSUE THREAD

**Issue by csmarc** [openssi/peer-did-method-spec#60]
I really like the revised Introduction section. However, as I understand, anywise DIDs will be usually "normal" anchored DIDs on public ledgers. This is expressed more explicitly in Sec. 1.3. However, I think we could give a simple note about this to the reader already in the beginning of the Introduction.

"Generally, an anywise DID needs to be resolvable by strangers (i.e. publicly anchored DID). These strangers can use the DID to reference its subject (usually by resolving it on a public ledger) without establishing a relationship."

**Comment by dhh1128** [comment]
Fixed in PR #69
