### ISSUE TITLE
Inviter must verify that DID received in exchange request was generated from correct public key

### ISSUE THREAD

**Issue by SvenHammann90** [openssi/peer-did-method-spec#74]
Hi all,

I have been working on formal verification using the Tamarin prover for my RWOT topic paper and encountered a potential issue. 

This specification states that man-in-the-middle attacks are excluded due to the way DIDs are generated from their (stored versions of) the DID documents. For this guarantee to hold, the inviter MUST verify for a DID + DID Doc they receive as an exchange request, that the DID was properly generated, using the algorithm from the (stored version of) the received DID Doc.

If this check is not performed, an attacker can insert a public key they control, while the DID would still look as if it belonged to the invitee. I describe the details of the attack in the long version of my RWOT topic paper, located at: https://github.com/SvenHammann90/SSI/blob/master/RWOT_9/Topic_Paper_RWOT.md

I believe the necessity for this check should be described in the doc, but I was not sure where it best fits (security considerations or the protocol itself?) and how to exactly phrase it, thus an issue and not a pull request.

Thank you for looking at this,
Sven

**Comment by dhh1128** [comment]
I agree. Good issue. Thanks, @SvenHammann90 !

I'm thinking that this goes in both places you mentioned. I don't mind writing up something, but I'd prefer to have you credited and listed as a contributor and author. Do you mind either A) proposing something as a PR; or B) letting me writing up a PR that credits you as the author and me as the committer, and handing it to you for review before merging?

**Comment by SvenHammann90** [comment]
You are welcome! I would be very happy to become a contributor/author. I will propose a PR, but please feel free to re-write it as you see fit, as I do not have much experience with writing specifications.

I plan on submitting a PR today (note: afterwards, I will be on holidays for two weeks, so feel free to do textual changes without asking back).

Small addition: If I understand correctly, the protocol part refers to [Aries RFC 0023](https://github.com/hyperledger/aries-rfcs/blob/master/features/0023-did-exchange/README.md), and serves only as a summary. To be consistent, I believe we would need a change there as well. Would it make sense to propose a PR there as well?

**Comment by dhh1128** [comment]
Thank you, Sven. Your PR is merged.

I would like to credit you as an author. I have added you to the author's
list at the front <https://openssi.github.io/peer-did-method-spec/>, but
all I have is a name, which I derived from your Github handle. I'm not sure
I got it right. Would you like me to include an affiliation to a company or
school, as other authors have? Please let me know your preference.

**Comment by SvenHammann90** [comment]
Hello Daniel,
(I suppose using first names is fine around here?)

Thank you very much. You did get my name right. I am a PhD student at the Information Security Group at ETH Zurich, Switzerland. If you could write "(ETH Zurich)", that would be good. As a link, this one would be great, as it links directly to the group I'm part of:
https://infsec.ethz.ch/

Thank you,
Sven

**Comment by dhh1128** [comment]
Done. https://github.com/openssi/peer-did-method-spec/pull/85.

See my mentions of you in issues #82 and #84.

**Comment by dhh1128** [comment]
This issue should have been closed long ago. Just housekeeping.
