### ISSUE TITLE
turn on DCO

### ISSUE THREAD

**Issue by dhh1128** [openssi/peer-did-method-spec#82]
I would like to turn on the [DCO bot](https://github.com/apps/dco), and to go back through history and add a `Signed-off-by` note to any commits that lack it. Do any of our contributors object? @kdenhartog @TelegramSam @csmarc @Oskar-van-Deventer @SvenHammann90 @devin-fisher @brentzundel @mavarley

Background:

It's not clear whether this spec will end up being sponsored in a formal way by any standards body or open source umbrella project--but it seems moderately likely that one or more of the [W3C](https://w3c-ccg.github.io/), [DIF](https://identity.foundation), and/or [Hyperledger](https://www.hyperledger.org/) might endorse it officially.

If that happens, one of the issues that will arise is whether all contributors to a spec are officially aligned with this repo's Apache 2 license (which has always been here). Specifically, they will want to be sure that nothing in the spec is encumbered by copyright or patents in any way.

Github has a way to officially prove that, which is through the [DCO bot](https://github.com/apps/dco). I can turn that on now, which will begin enforcement from this point forward. I can also modify the log message from any old commits to clarify that this was the case for them, too. But I don't want to modify old commit messages from any of you unless you are comfortable with me doing so.

For reference, this is common practice in Hyperledger, where I have done a lot of work, because it makes all the lawyers happy and it forces collaborating developers to be crisp about IP.

**Comment by SvenHammann90** [comment]
I agree to this, including modification of my old commit messages.

Kind Regards,
Sven

**Comment by kdenhartog** [comment]
I believe I've been using DCO commit methods anyways. I'll double check my commits and amend them if they have problems.

**Comment by brentzundel** [comment]
I believe my commits are all signed as well, but will amend them if needed.

**Comment by csmarc** [comment]
I agree to this as well, and I turned on DCO.

**Comment by Oskar-van-Deventer** [comment]
I have no objection at turning on DCO, though I may need some help to get my PR's properly DCO-ed ...

By the way, what refrains us from moving the whole Peer DID spec to Hyperledger Aries?
(I don't know the history of openssi, so please pardon my ignorance)

Oskar

**Comment by dhh1128** [comment]
Moving this spec to a more permanent home is probably a good idea. However, all the candidates for a permanent homes had political problems when I began the work. Therefore, I deliberately placed this spec in the most generic, most unaffiliated place I could think of, for the time being, because I wanted it not to be strongly associated with any particular sponsor. I wanted people who encountered it to just evaluate it on the basis of its ideas, and to defer the question of its home (which is secondary) until later. Now that we have a significant collection of authors, I think we can ask them where they want to move it, and start developing a consensus about that question. I'll open a separate ticket about that.

**Comment by dhh1128** [comment]
@peacekeeper , I can't see the settings on our new repo at DIF. Can you confirm that DCO check is enabled there?

**Comment by dhh1128** [comment]
Opened a related issue in the new repo home: https://github.com/decentralized-identity/peer-did-method-spec/issues/18.
