### ISSUE TITLE
Improve introduction by citing use cases.

### ISSUE THREAD

**Issue by vinomaster** [openssi/peer-did-method-spec#99]
Helping readings of the spec understand by-example the power of the peer to peer architecture would help improve the readability of the spec. For example, I suggest the following changes (~line 92 of intro.html) that emphasizes its peer-to-peer sweet spot:

_Because they avoid a dependence on a central source of truth, peer DIDs free themselves of the often-online requirement that typifies most other DID methods, and are thus well suited to <a target="aries" href="https://github.com/hyperledger/aries-rfcs/blob/master/features/0116-evidence-exchange/README.md"> use cases that need a decentralized peer-oriented architecture</a>. Peer DIDs can be created and maintained for an entire lifecycle without any reliance on the internet, with no degradation of trust. They thus align closely with the ethos and the architectural mindset of the <a href="https://www.inkandswitch.com/local-first.html"
target="_blank">local-first</a> and <a target="_blank" href="http://offlinefirst.org/">offline-first</a> software movements._

**Comment by dhh1128** [comment]
Resolved in PR #102
